
const gallery = [
    {src: `${import.meta.env.BASE_URL}tours/chike-taman-pereval.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/cvadro-1.png`},
    {src: `${import.meta.env.BASE_URL}tours/golden-baba.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/haski-1.png`},
    {src: `${import.meta.env.BASE_URL}tours/forel.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/zubr-pitomnik-2.png`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-4.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-1.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/zubr-pitomnik.png`},
    {src: `${import.meta.env.BASE_URL}tours/waterfall.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/tavdin-cave-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/tavdin-cave.jpeg`},
    {src: `${import.meta.env.BASE_URL}images/bg-3.jpg`},
    {src: `${import.meta.env.BASE_URL}images/bg-4.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/semenski-pereval.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-4.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed3-1.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/museum.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-canat-2.png`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-canat-1.png`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-1.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-2.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-3.jpg`},
    {src: `${import.meta.env.BASE_URL}images/img-4.jpg`},
    {src: `${import.meta.env.BASE_URL}images/bg-1.jpg`},
    {src: `${import.meta.env.BASE_URL}images/bg-2.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-2.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-3.jpg`},
]

export default gallery;