
const gallery = [
    {src: `${import.meta.env.BASE_URL}tours/chike-taman-pereval.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/cvadrocicle.webp`},
    {src: `${import.meta.env.BASE_URL}tours/golden-baba.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/haski.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/hram-apostola.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/lohmataya-2.png`},
    {src: `${import.meta.env.BASE_URL}tours/lohmataya.png`},
    {src: `${import.meta.env.BASE_URL}tours/golden-baba-2.jpeg`},
    {src: `${import.meta.env.BASE_URL}tours/zubr-pitomnik-2.png`},
    {src: `${import.meta.env.BASE_URL}tours/zubr-pitomnik.png`},
    {src: `${import.meta.env.BASE_URL}tours/waterfall.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/tour-2.webp`},
    {src: `${import.meta.env.BASE_URL}tours/tavdin-cave-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/tour-2.webp`},
    {src: `${import.meta.env.BASE_URL}tours/tavdin-cave.jpeg`},
    {src: `${import.meta.env.BASE_URL}tours/semenski-pereval.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/rynok-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/rynok.jpeg`},
    {src: `${import.meta.env.BASE_URL}tours/paseka-2.jpeg`},
    {src: `${import.meta.env.BASE_URL}tours/paseka.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/museum.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-canat-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-canat.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok-2.jpg`},
    {src: `${import.meta.env.BASE_URL}tours/manzherok.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-1.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-2.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-3.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-4.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-5.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-6.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-7.jpg`},
    {src: `${import.meta.env.BASE_URL}photos/img-8.jpg`},,
    {src: `${import.meta.env.BASE_URL}images/altay-1.jpg`},
    {src: `${import.meta.env.BASE_URL}images/altay-2.jpg`},
    {src: `${import.meta.env.BASE_URL}images/altay-3.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-1.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-2.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-3.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-4.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed1-5.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-1.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-2.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-3.jpg`},
    {src: `${import.meta.env.BASE_URL}feedbacks/feed2-4.jpg`},
]

export default gallery;